image: node:latest

cache:
  paths:
    - node_modules/

before_script:
  - npm i -g gatsby-cli
  - export PATH="$PATH:/usr/local/bin/gatsby"

stages:
    - testing

testing:
  stage: test
  script:
    - npm i
    - npm test
    - npm run build
  artifacts:
    paths:
      - public

# deployment:
#     stage: deploy
#     script: aws s3 sync ./public s3://beta.matthiaskretschmann.com --delete --acl public-read
#     only:
#         - master
