image: node:latest

cache:
  paths:
    - node_modules/

testing:
  stage: test
  script:
    - npm i
    - npm test
    - ./node_modules/gatsby/dist/bin/gatsby.js build
  artifacts:
    paths:
      - public
