cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:
  image: node:latest
  stage: build
  script:
    - npm i -g gatsby-cli
    - export PATH="$PATH:/usr/local/bin/gatsby"
    - npm i
    - npm test
    - npm run build
  artifacts:
    paths:
      - public

deploy:
  image: garland/aws-cli-docker:latest
  stage: deploy
  script:
    - aws s3 sync ./public s3://beta.matthiaskretschmann.com --delete --acl public-read
  only:
    - master
