image: node:latest

cache:
  paths:
    - node_modules/

before_script:
  - apt-get update -qq
  - apt-get install -y libx11-xcb1 libxcomposite1 libxcursor1 libxfixes3 libxdamage1 libxi6

testing:
  stage: test
  script:
    - npm install
    - npm test
    - npm run build
