dist: xenial
language: node_js
node_js: node

cache:
  npm: true
  directories:
    - public

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install python3-pip
  - sudo -H pip3 install --upgrade pip

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - "./cc-test-reporter before-build"

script:
  - npm test
  - npm run build

after_script:
  - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"

after_success:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - npm run deploy
  - npm run lh -- https://beta.matthiaskretschmann.com

notifications:
  email: false
  slack:
    secure: L/4F9a/2rZ32kCkypn6242HYD9PDd9XY8Ir751rIncn5kRH9beEOV96z9ya9zEZnz42nmCXmGQh5rjxJyeNJmRv+qJa6zoFx3mSkE/cJToIkuir/87gadJLk8wWnFkg5Cu0k0SacBy6iCoilUAo2BC1jJiyPOqCH/0VP8sseEh+0GGuda+LtGVZpfcyHXTN7PRhefq/ERyzIARgEamQSEGyTkTuU5HvV3z5azwUQri04E1sLIiuITZIoRw1H6rydEOrH5R8Jw629XMvurztu5T7C+zY32fno7NjWsQ2BDzf7uoCmEfaS7sNk1S8rI5RLyGzPQdrT57Dmd9WW4Yj+8U2BHIMIoRNqM62B7iALpzWHpjFwbsbABsqyM78kmcaNdiT5X/zst8DYsTSklTcVLfUCJR+KT2SVhQcevyxHtUVegre0YuYmzDee9Pg35VCtHDKBjvuUgUoKA0/hLhMHMcEKLetCTJ6iTmhnQWMsuznhlo0UgoXPWWOKi08KW6NPUhzqffD/71sO1gSXWzYMx3kWHiT42mUZL72SAYA33fJyMtfQCdztaVqPEP4t7YVAf6XK47oi7/hZ6pHAWf2YioryBzw0M+b3KzZvLLXgpIPJO5GaqRtkRpVIC91Xc7iQTBnhhgf37HAyOsxR4LZsAq66GwzGJWshx7EY5ZqVHVs=
