sudo: required
language: node_js
node_js: node

addons:
  chrome: stable

cache:
  directories:
    - node_modules
    - public

install:
  - npm i

before_script:
  - export DISPLAY=:99.0
  - export CHROME_PATH="$(pwd)/chrome-linux/chrome"
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # wait for xvfb to boot

script:
  - npm test
  - npm run build

after_success:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - npm run deploy

notifications:
  email: false
  slack:
    secure: TFQ8YZ9ZbmTXK8KZ1vRtDfbimwgC+e/m4cyT5rdD8za1+rhUKJ7FVDg6aqPQuURQbsk/jR/BjTEIKEnvg7tB3GyQayaUDA/J2DE3ok1KJKsZku0H+ombvk7iAeqhxghDx9R/+yWKGFShgEE7mMYGGgOM8Udb9UIfVwXvx+4OnD0tXzKiEE0Zdg3TP+25ex05T9o3VPxLaPLSZCFC+7YwAE8foGG5pmT/tReCuiIUwupxcNcqY6wovxFeEzDXqdQ0jsrZz+HZsVqZUu4Z7TjAkIyL9y5QrAbPQ2dBiTxG5VsgR8YJsyK5DPJ7DeBielLaGOoakC4U5RIvR1jPwIDWcpd/UY3AZsSc3bLbtNn2/E2cbGFzMFiO+qBZmBOxS6tDM7SvlDNYD/wDINv/Bpa4MHN6h3mY1TpgYSFf8Gke/dlZcGmRhDoG1uC8BKSIDT9+o3rhIxv8sYKDuN7U0zY02jGU5kfzQkKqKP9rl4zI+Zj0ClkjUa4t1CUNDuExmjtsrp2JQzSGmTy/ofpqizDiK+P84nCxv5BmNV8ZEE/d6AD8TBNp1jjeGmT43U34TjirtBPyDVHl7BDicw7TnwnvOsR1Xqs5l7f2XleQsb4zHqHQQzGByuF9uSAwUJYe2MCJMAy34qrVCe8vrLPhCA7lMj5uamMTPYbMD48Df/AmeRw=
